[Login]
HandlePowerKey=suspend
HandlePowerKeyLongPress=poweroff
HandleSuspendKey=suspend
HandleSuspendKeyLongPress=poweroff
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
